In [1]:
import pandas as pd
import re

In [2]:
# Load CSV paragraph
df_data_paragraph = pd.read_csv('material_book_1_paragraph.csv')

# Load CSV other
df_data_table = pd.read_csv('material_book_1_other.csv')

## Tambahkan kolom label_id

In [3]:
df_data_paragraph['label_id']=""

In [4]:
df_data_paragraph['label']=""

# Bahan Dasar (5-11)

## Worship - 4

## Prayer - 2

## Shermon - 3

In [5]:
df_data_paragraph.loc[106:116,'label_id']=3
df_data_paragraph.loc[106:116,'label']="Sermon"

## Announcement - 1

In [6]:
df_data_paragraph.loc[117:128,'label_id']=1
df_data_paragraph.loc[117:128,'label']="Announcement"

# Minggu VI ~ Minggu Paska (71-130)

## Prayer - 2

In [7]:
# 93-
df_data_paragraph.loc[549:549,'label_id']=2
df_data_paragraph.loc[549:549,'label']="Prayer"
# 123-
df_data_paragraph.loc[673:673,'label_id']=2
df_data_paragraph.loc[673:673,'label']="Prayer"

## Shermon - 3

In [8]:
# 71-78 
df_data_paragraph.loc[427:465,'label_id']=3
df_data_paragraph.loc[427:465,'label']="Sermon"

# 79-91
df_data_paragraph.loc[467:516,'label_id']=3
df_data_paragraph.loc[467:516,'label']="Sermon"

# 93-100
df_data_paragraph.loc[519:548,'label_id']=3
df_data_paragraph.loc[519:548,'label']="Sermon"
# -- (2)
df_data_paragraph.loc[550:555,'label_id']=3
df_data_paragraph.loc[550:555,'label']="Sermon"

# 101-108
df_data_paragraph.loc[557:588,'label_id']=3
df_data_paragraph.loc[557:588,'label']="Sermon"

# 109-121
df_data_paragraph.loc[590:627,'label_id']=3
df_data_paragraph.loc[590:627,'label']="Sermon"
# --(2)
df_data_paragraph.loc[632:643,'label_id']=3
df_data_paragraph.loc[632:643,'label']="Sermon"

# 123-
df_data_paragraph.loc[646:672,'label_id']=3
df_data_paragraph.loc[646:672,'label']="Sermon"

## Worship - 4

In [9]:
# 101-121
df_data_paragraph.loc[628:631,'label_id']=4
df_data_paragraph.loc[628:631,'label']="Worship"

## Announcement - 1

In [10]:
df_data_paragraph.loc[117:128,'label_id']=1
df_data_paragraph.loc[117:128,'label']="Announcement"

# Minggu VI ~ Minggu Paska Sore (181-223)

## Prayer - 2

In [11]:
# 181-189
df_data_paragraph.loc[1391:1396,'label_id']=2
df_data_paragraph.loc[1391:1396,'label']="Prayer"
# --(2)
df_data_paragraph.loc[1423:1425,'label_id']=2
df_data_paragraph.loc[1423:1425,'label']="Prayer"

# 190-199
x1 = df_data_paragraph.loc[(df_data_paragraph.style_left.str.contains("720"))&
                     (df_data_paragraph.VALUE.str.contains(""))
                     ].loc[1529:1544]
df_data_paragraph.loc[df_data_paragraph.index.to_series().apply(lambda x: x in x1.index),'label_id']=2

x2 = df_data_paragraph.loc[(df_data_paragraph.style_left.str.contains("720"))&
                     (df_data_paragraph.VALUE.str.contains(""))
                     ].loc[1529:1544]
df_data_paragraph.loc[df_data_paragraph.index.to_series().apply(lambda x: x in x2.index),'label']="Prayer"

#199-207
df_data_paragraph.loc[1688:1693,'label_id']=2
df_data_paragraph.loc[1688:1693,'label']="Prayer"

x3 = df_data_paragraph.loc[(df_data_paragraph.style_left.str.contains(""))&
                     (df_data_paragraph.VALUE.str.contains(""))
                     ].loc[1688:1693]
df_data_paragraph.loc[df_data_paragraph.index.to_series().apply(lambda x: x in x3.index),'label_id']=2
df_data_paragraph.loc[df_data_paragraph.index.to_series().apply(lambda x: x in x3.index),'label']="Prayer"

x4 = df_data_paragraph.loc[(df_data_paragraph.style_left.str.contains(""))&
                     (df_data_paragraph.VALUE.str.contains(""))
                     ].loc[1673:1677]
df_data_paragraph.loc[df_data_paragraph.index.to_series().apply(lambda x: x in x4.index),'label_id']=2
df_data_paragraph.loc[df_data_paragraph.index.to_series().apply(lambda x: x in x4.index),'label']="Prayer"

# 208-213 1779:1865
x208_213_1 = df_data_paragraph.loc[(df_data_paragraph.style_left.str.contains(""))&
                     (df_data_paragraph.VALUE.str.contains(""))
                     ].loc[1787:1792]
df_data_paragraph.loc[df_data_paragraph.index.to_series().apply(lambda x: x in x208_213_1.index),'label_id']=2
df_data_paragraph.loc[df_data_paragraph.index.to_series().apply(lambda x: x in x208_213_1.index),'label']="Prayer"
# --(2)
x208_213_2 = df_data_paragraph.loc[(df_data_paragraph.style_left.str.contains(""))&
                     (df_data_paragraph.VALUE.str.contains(""))
                     ].loc[1841:1851]
df_data_paragraph.loc[df_data_paragraph.index.to_series().apply(lambda x: x in x208_213_2.index),'label_id']=2
df_data_paragraph.loc[df_data_paragraph.index.to_series().apply(lambda x: x in x208_213_2.index),'label']="Prayer"

# 214 - 223 1866:2010
df_data_paragraph.loc[1895:1900,'label_id']=2
df_data_paragraph.loc[1895:1900,'label']="Prayer"
# --(2)
df_data_paragraph.loc[1917:1919,'label_id']=2
df_data_paragraph.loc[1917:1919,'label']="Prayer"

# 224-230 2011:2109
df_data_paragraph.loc[2034:2039,'label_id']=2
df_data_paragraph.loc[2034:2039,'label']="Prayer"
# --(2)
df_data_paragraph.loc[2056:2068,'label_id']=2
df_data_paragraph.loc[2056:2068,'label']="Prayer"
# --(3)
df_data_paragraph.loc[2071:2077,'label_id']=2
df_data_paragraph.loc[2071:2077,'label']="Prayer"

## Shermon - 3

## Worship - 4

In [12]:
# 181-189
df_data_paragraph.loc[1347:1355,'label_id']=4
df_data_paragraph.loc[1347:1355,'label']="Worship"
# --(2)
df_data_paragraph.loc[1358:1359,'label_id']=4
df_data_paragraph.loc[1358:1359,'label']="Worship"
# --(3)
df_data_paragraph.loc[1365:1370,'label_id']=4
df_data_paragraph.loc[1365:1370,'label']="Worship"
# --(4)
df_data_paragraph.loc[1375:1378,'label_id']=4
df_data_paragraph.loc[1375:1378,'label']="Worship"
# --(5)
df_data_paragraph.loc[1383:1390,'label_id']=4
df_data_paragraph.loc[1383:1390,'label']="Worship"
# --(6)
df_data_paragraph.loc[[1398,1401,1404,1407,1410,1412,1414,1416,1418,1420],'label_id']=4
df_data_paragraph.loc[[1398,1401,1404,1407,1410,1412,1414,1416,1418,1420],'label']="Worship"
# --(7)
df_data_paragraph.loc[1429:1431,'label_id']=4
df_data_paragraph.loc[1429:1431,'label']="Worship"
# --(8)
df_data_paragraph.loc[1441:1454,'label_id']=4
df_data_paragraph.loc[1441:1454,'label']="Worship"
# --(9)
df_data_paragraph.loc[1458:1472,'label_id']=4
df_data_paragraph.loc[1458:1472,'label']="Worship"
# --(10)
df_data_paragraph.loc[1485:1485,'label_id']=4
df_data_paragraph.loc[1485:1485,'label']="Worship"

# 190-198
x1 = df_data_paragraph.loc[(df_data_paragraph.style_left.str.contains("1080"))&
                     (df_data_paragraph.VALUE.str.contains(""))
                     ].loc[1491:1700]
df_data_paragraph.loc[(df_data_paragraph.index.to_series().apply(lambda x: x in x1.index)),'label_id']=4
df_data_paragraph.loc[df_data_paragraph.index.to_series().apply(lambda x: x in x1.index),'label']="Worship"

#199-207
df_data_paragraph.loc[1755:1758,'label_id']=4
df_data_paragraph.loc[1755:1758,'label']="Worship"
# --(2)
x2 = df_data_paragraph.loc[(df_data_paragraph.style_left.str.contains("426"))&
                     (df_data_paragraph.VALUE.str.contains(""))
                     ].loc[1703:1770]
df_data_paragraph.loc[(df_data_paragraph.index.to_series().apply(lambda x: x in x2.index)),'label_id']=4
df_data_paragraph.loc[df_data_paragraph.index.to_series().apply(lambda x: x in x2.index),'label']="Worship"
# --(3)
x3 = df_data_paragraph.loc[(df_data_paragraph.style_left.str.contains("993"))&
                     (df_data_paragraph.VALUE.str.contains(""))
                     ].loc[1654:1770]
df_data_paragraph.loc[(df_data_paragraph.index.to_series().apply(lambda x: x in x3.index)),'label_id']=4
df_data_paragraph.loc[df_data_paragraph.index.to_series().apply(lambda x: x in x3.index),'label']="Worship"
# --(4)
df_data_paragraph.loc[1776:1776,'label_id']=4
df_data_paragraph.loc[1776:1776,'label']="Worship"

# 208-213 1779:1865
x208_213_1 = df_data_paragraph.loc[(df_data_paragraph.style_left.str.contains("900"))&
                     (df_data_paragraph.VALUE.str.contains(""))
                     ].loc[1779:1865]
df_data_paragraph.loc[(df_data_paragraph.index.to_series().apply(lambda x: x in x208_213_1.index)),'label_id']=4
df_data_paragraph.loc[df_data_paragraph.index.to_series().apply(lambda x: x in x208_213_1.index),'label']="Worship"
# --(2)
x208_213_2 = df_data_paragraph.loc[(df_data_paragraph.style_left.str.contains("990"))&
                     (df_data_paragraph.VALUE.str.contains(""))
                     ].loc[1779:1865]
df_data_paragraph.loc[(df_data_paragraph.index.to_series().apply(lambda x: x in x208_213_2.index)),'label_id']=4
df_data_paragraph.loc[df_data_paragraph.index.to_series().apply(lambda x: x in x208_213_2.index),'label']="Worship"

# 214 - 223 1866:2010
x214_223_1 = df_data_paragraph.loc[(df_data_paragraph.style_left.str.contains("426"))&
                     (df_data_paragraph.VALUE.str.contains(""))
                     ].loc[1866:2010].iloc[:-1]
df_data_paragraph.loc[(df_data_paragraph.index.to_series().apply(lambda x: x in x214_223_1.index)),'label_id']=4
df_data_paragraph.loc[df_data_paragraph.index.to_series().apply(lambda x: x in x214_223_1.index),'label']="Worship"
# --(2)
df_data_paragraph.loc[1920:1924,'label_id']=4
df_data_paragraph.loc[1920:1924,'label']="Worship"
# --(3)
x214_223_2 = df_data_paragraph.loc[(df_data_paragraph.style_left.str.contains("993"))&
                     (df_data_paragraph.VALUE.str.contains(""))
                     ].loc[1866:2010]
df_data_paragraph.loc[(df_data_paragraph.index.to_series().apply(lambda x: x in x214_223_2.index)),'label_id']=4
df_data_paragraph.loc[df_data_paragraph.index.to_series().apply(lambda x: x in x214_223_2.index),'label']="Worship"

#224-230 2011:2109
df_data_paragraph.loc[2098:2101,'label_id']=4
df_data_paragraph.loc[2098:2101,'label']="Worship"
# --(2)
x224_230_1 = df_data_paragraph.loc[(df_data_paragraph.style_left.str.contains("993"))&
                     (df_data_paragraph.VALUE.str.contains(""))
                     ].loc[2011:2109].iloc[:]
df_data_paragraph.loc[(df_data_paragraph.index.to_series().apply(lambda x: x in x224_230_1.index)),'label_id']=4
df_data_paragraph.loc[df_data_paragraph.index.to_series().apply(lambda x: x in x224_230_1.index),'label']="Worship"
# --(3)

## Announcement - 1

In [13]:
# 181-189
df_data_paragraph.loc[1357:1357,'label_id']=1
df_data_paragraph.loc[1357:1357,'label']="Announcement"
# --(2)
df_data_paragraph.loc[1426:1428,'label_id']=1
df_data_paragraph.loc[1426:1428,'label']="Announcement"
# --(3)
df_data_paragraph.loc[1432:1432,'label_id']=1
df_data_paragraph.loc[1432:1432,'label']="Announcement"
# --(4)
df_data_paragraph.loc[1435:1436,'label_id']=1
df_data_paragraph.loc[1435:1436,'label']="Announcement"
# --(5)
df_data_paragraph.loc[1440:1440,'label_id']=1
df_data_paragraph.loc[1440:1440,'label']="Announcement"
# --(6)
df_data_paragraph.loc[1340:1347,'label_id']=1
df_data_paragraph.loc[1340:1347,'label']="Announcement"
# --(7)
df_data_paragraph.loc[1361:1364,'label_id']=1
df_data_paragraph.loc[1361:1364,'label']="Announcement"
# --(8)
df_data_paragraph.loc[1372:1372,'label_id']=1
df_data_paragraph.loc[1372:1372,'label']="Announcemen"
# --(9)
df_data_paragraph.loc[1380:1380,'label_id']=1
df_data_paragraph.loc[1380:1380,'label']="Announcement"
# --(10)
df_data_paragraph.loc[1474:1479,'label_id']=1
df_data_paragraph.loc[1474:1479,'label']="Announcement"
# --(11)
df_data_paragraph.loc[1481:1481,'label_id']=1
df_data_paragraph.loc[1481:1481,'label']="Announcement"

# 190-198
df_data_paragraph.loc[1489:1491,'label_id']=1
df_data_paragraph.loc[1489:1491,'label']="Announcement"
# --(2)
x1 = df_data_paragraph.loc[(df_data_paragraph.style_left.str.contains("720"))&
                     (df_data_paragraph.VALUE.str.contains(""))
                     ].loc[1491:1700]
xPray = df_data_paragraph.loc[(df_data_paragraph.style_left.str.contains("720"))&
                     (df_data_paragraph.VALUE.str.contains(""))
                     ].loc[1529:1544]
df_data_paragraph.loc[(df_data_paragraph.index.to_series().apply(lambda x: x in x1.index))&
                      (df_data_paragraph.index.to_series().apply(lambda x: x not in xPray.index))
                      ,'label_id']=1
df_data_paragraph.loc[(df_data_paragraph.index.to_series().apply(lambda x: x in x1.index))&
                      (df_data_paragraph.index.to_series().apply(lambda x: x not in xPray.index))
                      ,'label']="Announcement"

#199-207
x2 = df_data_paragraph.loc[(df_data_paragraph.style_left.str.contains("567"))&
                     (df_data_paragraph.VALUE.str.contains(""))
                     ].loc[1650:1777]
xPray2 = df_data_paragraph.loc[(df_data_paragraph.style_left.str.contains(""))&
                     (df_data_paragraph.VALUE.str.contains(""))
                     ].loc[1688:1693]
xPray3 = df_data_paragraph.loc[(df_data_paragraph.style_left.str.contains(""))&
                     (df_data_paragraph.VALUE.str.contains(""))
                     ].loc[1673:1677]
xSong = df_data_paragraph.loc[1776:1776]

df_data_paragraph.loc[(df_data_paragraph.index.to_series().apply(lambda x: x in x2.index))&
                      (df_data_paragraph.index.to_series().apply(lambda x: x not in xPray2.index))&
                      (df_data_paragraph.index.to_series().apply(lambda x: x not in xPray3.index))&
                      (df_data_paragraph.index.to_series().apply(lambda x: x not in xSong.index))
                      ,'label_id']=1
df_data_paragraph.loc[(df_data_paragraph.index.to_series().apply(lambda x: x in x2.index))&
                      (df_data_paragraph.index.to_series().apply(lambda x: x not in xPray2.index))&
                      (df_data_paragraph.index.to_series().apply(lambda x: x not in xPray3.index))&
                      (df_data_paragraph.index.to_series().apply(lambda x: x not in xSong.index))
                      ,'label']="Announcement"

# 208-213  1779:1865
x208_213=df_data_paragraph.loc[(df_data_paragraph.style_left.str.contains("567"))&
                     (df_data_paragraph.VALUE.str.contains(""))
                     ].loc[1779:1865]
x208_213Prayer1=df_data_paragraph.loc[(df_data_paragraph.style_left.str.contains(""))&
                     (df_data_paragraph.VALUE.str.contains(""))
                     ].loc[1787:1792]
x208_213Prayer2=df_data_paragraph.loc[(df_data_paragraph.style_left.str.contains(""))&
                     (df_data_paragraph.VALUE.str.contains(""))
                     ].loc[1841:1851]
df_data_paragraph.loc[(df_data_paragraph.index.to_series().apply(lambda x: x in x208_213.index))&
                      (df_data_paragraph.index.to_series().apply(lambda x: x not in x208_213Prayer1.index))&
                      (df_data_paragraph.index.to_series().apply(lambda x: x not in x208_213Prayer2.index))
                      ,'label_id']=1
df_data_paragraph.loc[(df_data_paragraph.index.to_series().apply(lambda x: x in x208_213.index))&
                      (df_data_paragraph.index.to_series().apply(lambda x: x not in x208_213Prayer1.index))&
                      (df_data_paragraph.index.to_series().apply(lambda x: x not in x208_213Prayer2.index))
                      ,'label']="Announcement"

# 214 - 223 1866:2010
x214_223_1=df_data_paragraph.loc[(df_data_paragraph.style_left.str.contains("567"))&
                     (df_data_paragraph.VALUE.str.contains(""))
                     ].loc[1866:2010]
x214_223_prayer_1 = df_data_paragraph.loc[(df_data_paragraph.style_left.str.contains(""))&
                     (df_data_paragraph.VALUE.str.contains(""))
                     ].loc[1895:1900]
x214_223_prayer_2 = df_data_paragraph.loc[(df_data_paragraph.style_left.str.contains(""))&
                     (df_data_paragraph.VALUE.str.contains(""))
                     ].loc[1917:1919]
df_data_paragraph.loc[(df_data_paragraph.index.to_series().apply(lambda x: x in x214_223_1.index))&
                      (df_data_paragraph.index.to_series().apply(lambda x: x not in x214_223_prayer_1.index))&
                      (df_data_paragraph.index.to_series().apply(lambda x: x not in x214_223_prayer_2.index))
                      ,'label_id']=1
df_data_paragraph.loc[(df_data_paragraph.index.to_series().apply(lambda x: x in x214_223_1.index))&
                      (df_data_paragraph.index.to_series().apply(lambda x: x not in x214_223_prayer_1.index))&
                      (df_data_paragraph.index.to_series().apply(lambda x: x not in x214_223_prayer_2.index))
                      ,'label']="Announcement"

#224-230 2011:2109
x224_230_1 = df_data_paragraph.loc[(df_data_paragraph.style_left.str.contains("567"))&
                     (df_data_paragraph.VALUE.str.contains(""))
                     ].loc[2011:2109]
x224_230_song_1 = df_data_paragraph.loc[2098:2101]
x224_230_prayer_1 = df_data_paragraph.loc[(df_data_paragraph.style_left.str.contains(""))&
                     (df_data_paragraph.VALUE.str.contains(""))
                     ].loc[2034:2039]
x224_230_prayer_2 = df_data_paragraph.loc[(df_data_paragraph.style_left.str.contains(""))&
                     (df_data_paragraph.VALUE.str.contains(""))
                     ].loc[2056:2068]
x224_230_prayer_3 = df_data_paragraph.loc[(df_data_paragraph.style_left.str.contains(""))&
                     (df_data_paragraph.VALUE.str.contains(""))
                     ].loc[2071:2077]

df_data_paragraph.loc[(df_data_paragraph.index.to_series().apply(lambda x: x in x224_230_1.index))&
                      (df_data_paragraph.index.to_series().apply(lambda x: x not in x224_230_song_1.index))&
                      (df_data_paragraph.index.to_series().apply(lambda x: x not in x224_230_prayer_1.index))&
                      (df_data_paragraph.index.to_series().apply(lambda x: x not in x224_230_prayer_2.index))&
                      (df_data_paragraph.index.to_series().apply(lambda x: x not in x224_230_prayer_3.index))
                      ,'label_id']=1
df_data_paragraph.loc[(df_data_paragraph.index.to_series().apply(lambda x: x in x224_230_1.index))&
                      (df_data_paragraph.index.to_series().apply(lambda x: x not in x224_230_song_1.index))&
                      (df_data_paragraph.index.to_series().apply(lambda x: x not in x224_230_prayer_1.index))&
                      (df_data_paragraph.index.to_series().apply(lambda x: x not in x224_230_prayer_2.index))&
                      (df_data_paragraph.index.to_series().apply(lambda x: x not in x224_230_prayer_3.index))
                      ,'label']="Announcement"

# Pemuda1~Pemuda3 269-284

## Prayer - 2

In [14]:
# 269-274 2375:2408
# 275-279 2409:2447
# 281-284 2450:2474

## Shermon - 3

In [15]:
# 269-274 2375:2408
x269_274_1 = df_data_paragraph.loc[(df_data_paragraph.style_left.str.contains("\[\]"))&
                     (df_data_paragraph.VALUE.str.contains(""))
                     ].loc[2375:2408]
x269_274_worship_1 = df_data_paragraph.loc[(df_data_paragraph.style_left.str.contains(""))&
                     (df_data_paragraph.VALUE.str.contains(""))
                     ].loc[2378:2390]
df_data_paragraph.loc[(df_data_paragraph.index.to_series().apply(lambda x: x in x269_274_1.index))&
                      (df_data_paragraph.index.to_series().apply(lambda x: x not in x269_274_worship_1.index))
                      ,'label_id']=3
df_data_paragraph.loc[(df_data_paragraph.index.to_series().apply(lambda x: x in x269_274_1.index))&
                      (df_data_paragraph.index.to_series().apply(lambda x: x not in x269_274_worship_1.index))
                      ,'label']="Shermon"

# 275-279 2409:2447
x275_279_1 = df_data_paragraph.loc[(df_data_paragraph.style_left.str.contains(""))&
                     (df_data_paragraph.VALUE.str.contains(""))
                     ].loc[2410:2447]
x275_279_worship_1 = df_data_paragraph.loc[(df_data_paragraph.style_left.str.contains("360"))&
                     (df_data_paragraph.VALUE.str.contains(""))
                     ].loc[2415:2428]
df_data_paragraph.loc[(df_data_paragraph.index.to_series().apply(lambda x: x in x275_279_1.index))&
                      (df_data_paragraph.index.to_series().apply(lambda x: x not in x275_279_worship_1.index))
                      ,'label_id']=3
df_data_paragraph.loc[(df_data_paragraph.index.to_series().apply(lambda x: x in x275_279_1.index))&
                      (df_data_paragraph.index.to_series().apply(lambda x: x not in x275_279_worship_1.index))
                      ,'label']="Shermon"

# 281-284 2450:2474
df_data_paragraph.loc[2450:2474,'label_id']=3
df_data_paragraph.loc[2450:2474,'label']="Shermon"

## Worship - 4

In [16]:
# 269-274 2375:2408
x269_274_1 = df_data_paragraph.loc[(df_data_paragraph.style_left.str.contains(""))&
                     (df_data_paragraph.VALUE.str.contains(""))
                     ].loc[2378:2390]
df_data_paragraph.loc[(df_data_paragraph.index.to_series().apply(lambda x: x in x269_274_1.index))
                      ,'label_id']=4
df_data_paragraph.loc[(df_data_paragraph.index.to_series().apply(lambda x: x in x269_274_1.index))
                      ,'label']="Worship"

# 275-279 2409:2447
x275_279_1 = df_data_paragraph.loc[(df_data_paragraph.style_left.str.contains("360"))&
                     (df_data_paragraph.VALUE.str.contains(""))
                     ].loc[2415:2428]
df_data_paragraph.loc[(df_data_paragraph.index.to_series().apply(lambda x: x in x275_279_1.index))
                      ,'label_id']=4
df_data_paragraph.loc[(df_data_paragraph.index.to_series().apply(lambda x: x in x275_279_1.index))
                      ,'label']="Worship"

# 281-284 2450:2474

## Announcement - 1

In [17]:
# 269-274 2375:2408


# 275-279 2409:2447

# 281-284 2450:2474

# PA Adiyuswa 1~PA Adiyuswa 3 297-314

## Prayer - 2

## Shermon - 3

In [18]:
# 297-304 2450:2474
x297_304_1 = df_data_paragraph.loc[(df_data_paragraph.style_left.str.contains(""))&
                     (df_data_paragraph.VALUE.str.contains(""))
                     ].loc[2559:2612]
x297_304_announcement_1 = df_data_paragraph.loc[(df_data_paragraph.style_left.str.contains(""))&
                     (df_data_paragraph.VALUE.str.contains(""))
                     ].loc[2559:2561]
df_data_paragraph.loc[(df_data_paragraph.index.to_series().apply(lambda x: x in x297_304_1.index))&
                      (df_data_paragraph.index.to_series().apply(lambda x: x not in x297_304_announcement_1.index))
                      ,'label_id']=3
df_data_paragraph.loc[(df_data_paragraph.index.to_series().apply(lambda x: x in x297_304_1.index))&
                      (df_data_paragraph.index.to_series().apply(lambda x: x not in x297_304_announcement_1.index))
                      ,'label']="Shermon"   

# 305-309 2617:2647
x305_309_1 = df_data_paragraph.loc[(df_data_paragraph.style_left.str.contains(""))&
                     (df_data_paragraph.VALUE.str.contains(""))
                     ].loc[2617:2647]
x305_309_announcement_1 = df_data_paragraph.loc[(df_data_paragraph.style_left.str.contains(""))&
                     (df_data_paragraph.VALUE.str.contains(""))
                     ].loc[2617:2618]
df_data_paragraph.loc[(df_data_paragraph.index.to_series().apply(lambda x: x in x305_309_1.index))&
                      (df_data_paragraph.index.to_series().apply(lambda x: x not in x305_309_announcement_1.index))
                      ,'label_id']=3
df_data_paragraph.loc[(df_data_paragraph.index.to_series().apply(lambda x: x in x305_309_1.index))&
                      (df_data_paragraph.index.to_series().apply(lambda x: x not in x305_309_announcement_1.index))
                      ,'label']="Shermon"  

# 311-314 2652:2684
x311_314_1 = df_data_paragraph.loc[(df_data_paragraph.style_left.str.contains(""))&
                     (df_data_paragraph.VALUE.str.contains(""))
                     ].loc[2652:2684]
x311_314_announcement_1 = df_data_paragraph.loc[(df_data_paragraph.style_left.str.contains(""))&
                     (df_data_paragraph.VALUE.str.contains(""))
                     ].loc[2652:2653]
df_data_paragraph.loc[(df_data_paragraph.index.to_series().apply(lambda x: x in x311_314_1.index))&
                      (df_data_paragraph.index.to_series().apply(lambda x: x not in x311_314_announcement_1.index))
                      ,'label_id']=3
df_data_paragraph.loc[(df_data_paragraph.index.to_series().apply(lambda x: x in x311_314_1.index))&
                      (df_data_paragraph.index.to_series().apply(lambda x: x not in x311_314_announcement_1.index))
                      ,'label']="Shermon"

## Worship - 4

## Announcement - 1

In [19]:
# 297-304 2450:2474
x297_304_1 = df_data_paragraph.loc[(df_data_paragraph.style_left.str.contains(""))&
                     (df_data_paragraph.VALUE.str.contains(""))
                     ].loc[2559:2561]
df_data_paragraph.loc[(df_data_paragraph.index.to_series().apply(lambda x: x in x297_304_1.index))
                      ,'label_id']=1
df_data_paragraph.loc[(df_data_paragraph.index.to_series().apply(lambda x: x in x297_304_1.index))
                      ,'label']="Announcement"   

# 305-309 2617:2647
x305_309_1= df_data_paragraph.loc[(df_data_paragraph.style_left.str.contains(""))&
                     (df_data_paragraph.VALUE.str.contains(""))
                     ].loc[2617:2618]
df_data_paragraph.loc[(df_data_paragraph.index.to_series().apply(lambda x: x in x305_309_1.index))
                      ,'label_id']=1
df_data_paragraph.loc[(df_data_paragraph.index.to_series().apply(lambda x: x in x305_309_1.index))
                      ,'label']="Announcement"

# 311-314 2652:2684
x311_314_1 = df_data_paragraph.loc[(df_data_paragraph.style_left.str.contains(""))&
                     (df_data_paragraph.VALUE.str.contains(""))
                     ].loc[2652:2653]
df_data_paragraph.loc[(df_data_paragraph.index.to_series().apply(lambda x: x in x311_314_1.index))
                      ,'label_id']=1
df_data_paragraph.loc[(df_data_paragraph.index.to_series().apply(lambda x: x in x311_314_1.index))
                      ,'label']="Announcement"

# Persekutuan Doa 4~7 333-350

## Prayer - 2

In [20]:
# 333-336 2821:2868
x333_336_1 = df_data_paragraph.loc[(df_data_paragraph.style_left.str.contains(""))&
                     (df_data_paragraph.VALUE.str.contains(""))
                     ].loc[2861:2862]
df_data_paragraph.loc[(df_data_paragraph.index.to_series().apply(lambda x: x in x333_336_1.index))
                      ,'label_id']=2
df_data_paragraph.loc[(df_data_paragraph.index.to_series().apply(lambda x: x in x333_336_1.index))
                      ,'label']="Prayer"

# 337-340 2870:2917
x337_340_1 = df_data_paragraph.loc[(df_data_paragraph.style_left.str.contains(""))&
                     (df_data_paragraph.VALUE.str.contains(""))
                     ].loc[2909:2910]
df_data_paragraph.loc[(df_data_paragraph.index.to_series().apply(lambda x: x in x337_340_1.index))
                      ,'label_id']=2
df_data_paragraph.loc[(df_data_paragraph.index.to_series().apply(lambda x: x in x337_340_1.index))
                      ,'label']="Prayer"

# 341-345 2924:2985
x341_345_1 = df_data_paragraph.loc[(df_data_paragraph.style_left.str.contains(""))&
                     (df_data_paragraph.VALUE.str.contains(""))
                     ].loc[2973:2974]
df_data_paragraph.loc[(df_data_paragraph.index.to_series().apply(lambda x: x in x341_345_1.index))
                      ,'label_id']=2
df_data_paragraph.loc[(df_data_paragraph.index.to_series().apply(lambda x: x in x341_345_1.index))
                      ,'label']="Prayer"

# 345-349 2954:3030
x345_349_1 = df_data_paragraph.loc[(df_data_paragraph.style_left.str.contains(""))&
                     (df_data_paragraph.VALUE.str.contains(""))
                     ].loc[3021:3023]
df_data_paragraph.loc[(df_data_paragraph.index.to_series().apply(lambda x: x in x345_349_1.index))
                      ,'label_id']=2
df_data_paragraph.loc[(df_data_paragraph.index.to_series().apply(lambda x: x in x345_349_1.index))
                      ,'label']="Prayer"

## Shermon - 3

In [21]:
# 333-336 2821:2868
x333_336_1 = df_data_paragraph.loc[(df_data_paragraph.style_left.str.contains("567"))&
                     (df_data_paragraph.VALUE.str.contains(""))
                     ].loc[2837:2845]
df_data_paragraph.loc[(df_data_paragraph.index.to_series().apply(lambda x: x in x333_336_1.index))
                      ,'label_id']=3
df_data_paragraph.loc[(df_data_paragraph.index.to_series().apply(lambda x: x in x333_336_1.index))
                      ,'label']="Shermon"

# 337-340 2870:2917
x337_340_1=df_data_paragraph.loc[(df_data_paragraph.style_left.str.contains(""))&
                     (df_data_paragraph.VALUE.str.contains(""))
                     ].loc[2890:2901]
df_data_paragraph.loc[(df_data_paragraph.index.to_series().apply(lambda x: x in x337_340_1.index))
                      ,'label_id']=3
df_data_paragraph.loc[(df_data_paragraph.index.to_series().apply(lambda x: x in x337_340_1.index))
                      ,'label']="Shermon"

# 341-345 2924:2985
x341_345_1 = df_data_paragraph.loc[(df_data_paragraph.style_left.str.contains("567"))&
                     (df_data_paragraph.VALUE.str.contains(""))
                     ].loc[2948:2953]
df_data_paragraph.loc[(df_data_paragraph.index.to_series().apply(lambda x: x in x341_345_1.index))
                      ,'label_id']=3
df_data_paragraph.loc[(df_data_paragraph.index.to_series().apply(lambda x: x in x341_345_1.index))
                      ,'label']="Shermon"

# 345-349 2954:3030
x345_349_1 = df_data_paragraph.loc[(df_data_paragraph.style_left.str.contains("567"))&
                     (df_data_paragraph.VALUE.str.contains(""))
                     ].loc[3004:3011]
df_data_paragraph.loc[(df_data_paragraph.index.to_series().apply(lambda x: x in x345_349_1.index))
                      ,'label_id']=3
df_data_paragraph.loc[(df_data_paragraph.index.to_series().apply(lambda x: x in x345_349_1.index))
                      ,'label']="Shermon"

## Worship - 4

In [22]:
# 333-336 2821:2868
x333_336_1 = df_data_paragraph.loc[(df_data_paragraph.style_left.str.contains("993"))&
                     (df_data_paragraph.VALUE.str.contains(""))
                     ].loc[2821:2868]
df_data_paragraph.loc[(df_data_paragraph.index.to_series().apply(lambda x: x in x333_336_1.index))
                      ,'label_id']=4
df_data_paragraph.loc[(df_data_paragraph.index.to_series().apply(lambda x: x in x333_336_1.index))
                      ,'label']="Worship"

# 337-340 2870:2917
x337_340_1 = df_data_paragraph.loc[(df_data_paragraph.style_left.str.contains("993"))&
                     (df_data_paragraph.VALUE.str.contains(""))
                     ].loc[2870:2917]
x337_340_worship_1 = df_data_paragraph.loc[(df_data_paragraph.style_left.str.contains(""))&
                     (df_data_paragraph.VALUE.str.contains(""))
                     ].loc[2909:2910]
x337_340_prayer_1 =df_data_paragraph.loc[(df_data_paragraph.style_left.str.contains(""))&
                     (df_data_paragraph.VALUE.str.contains(""))
                     ].loc[2890:2901]

df_data_paragraph.loc[(df_data_paragraph.index.to_series().apply(lambda x: x in x337_340_1.index))&
                      (df_data_paragraph.index.to_series().apply(lambda x: x not in x337_340_worship_1.index))&
                      (df_data_paragraph.index.to_series().apply(lambda x: x not in x337_340_prayer_1.index))
                      ,'label_id']=4
df_data_paragraph.loc[(df_data_paragraph.index.to_series().apply(lambda x: x in x337_340_1.index))&
                      (df_data_paragraph.index.to_series().apply(lambda x: x not in x337_340_worship_1.index))&
                      (df_data_paragraph.index.to_series().apply(lambda x: x not in x337_340_prayer_1.index))
                      ,'label']="Worship"

# 341-345 2924:2985
x341_345_1 = df_data_paragraph.loc[(df_data_paragraph.style_left.str.contains("993"))&
                     (df_data_paragraph.VALUE.str.contains(""))
                     ].loc[2924:2985]
x341_345_prayer_1 = df_data_paragraph.loc[(df_data_paragraph.style_left.str.contains(""))&
                     (df_data_paragraph.VALUE.str.contains(""))
                     ].loc[2973:2974]

df_data_paragraph.loc[(df_data_paragraph.index.to_series().apply(lambda x: x in x341_345_1.index))&
                      (df_data_paragraph.index.to_series().apply(lambda x: x not in x341_345_prayer_1.index))
                      ,'label_id']=4
df_data_paragraph.loc[(df_data_paragraph.index.to_series().apply(lambda x: x in x341_345_1.index))&
                      (df_data_paragraph.index.to_series().apply(lambda x: x not in x341_345_prayer_1.index))
                      ,'label']="Worship"

# 345-349 2954:3030
x345_349_1 = df_data_paragraph.loc[(df_data_paragraph.style_left.str.contains("567"))&
                     (df_data_paragraph.VALUE.str.contains(""))
                     ].loc[2988:3030]
x345_349_shermon_1 = df_data_paragraph.loc[(df_data_paragraph.style_left.str.contains("567"))&
                     (df_data_paragraph.VALUE.str.contains(""))
                     ].loc[3004:3011]
df_data_paragraph.loc[(df_data_paragraph.index.to_series().apply(lambda x: x in x345_349_1.index))&
                      (df_data_paragraph.index.to_series().apply(lambda x: x not in x345_349_shermon_1.index))
                      ,'label_id']=4
df_data_paragraph.loc[(df_data_paragraph.index.to_series().apply(lambda x: x in x345_349_1.index))&
                      (df_data_paragraph.index.to_series().apply(lambda x: x not in x345_349_shermon_1.index))
                      ,'label']="Worship"
# --(2)
x345_349_2= df_data_paragraph.loc[(df_data_paragraph.style_left.str.contains(""))&
                     (df_data_paragraph.VALUE.str.contains(""))
                     ].loc[2998:3001]
df_data_paragraph.loc[(df_data_paragraph.index.to_series().apply(lambda x: x in x345_349_2.index))
                      ,'label_id']=4
df_data_paragraph.loc[(df_data_paragraph.index.to_series().apply(lambda x: x in x345_349_2.index))
                      ,'label']="Worship"

## Announcement - 1

In [23]:
# 333-336 2821:2868
x333_336_1 = df_data_paragraph.loc[(df_data_paragraph.style_left.str.contains(""))&
                     (df_data_paragraph.VALUE.str.contains(""))
                     ].loc[2821:2868]
x333_336_paryer_1 = df_data_paragraph.loc[(df_data_paragraph.style_left.str.contains(""))&
                     (df_data_paragraph.VALUE.str.contains(""))
                     ].loc[2861:2862]
x333_336_shermon_1 = df_data_paragraph.loc[(df_data_paragraph.style_left.str.contains("567"))&
                     (df_data_paragraph.VALUE.str.contains(""))
                     ].loc[2837:2845]
x333_336_worship_1 = df_data_paragraph.loc[(df_data_paragraph.style_left.str.contains("993"))&
                     (df_data_paragraph.VALUE.str.contains(""))
                     ].loc[2821:2868]
df_data_paragraph.loc[(df_data_paragraph.index.to_series().apply(lambda x: x in x333_336_1.index))&
                      (df_data_paragraph.index.to_series().apply(lambda x: x not in x333_336_paryer_1.index))&
                      (df_data_paragraph.index.to_series().apply(lambda x: x not in x333_336_shermon_1.index))&
                      (df_data_paragraph.index.to_series().apply(lambda x: x not in x333_336_worship_1.index))
                      ,'label_id']=1
df_data_paragraph.loc[(df_data_paragraph.index.to_series().apply(lambda x: x in x333_336_1.index))&
                      (df_data_paragraph.index.to_series().apply(lambda x: x not in x333_336_paryer_1.index))&
                      (df_data_paragraph.index.to_series().apply(lambda x: x not in x333_336_shermon_1.index))&
                      (df_data_paragraph.index.to_series().apply(lambda x: x not in x333_336_worship_1.index))
                      ,'label']="Announcement"

# 337-340 2870:2917
x337_340_1 = df_data_paragraph.loc[(df_data_paragraph.style_left.str.contains(""))&
                     (df_data_paragraph.VALUE.str.contains(""))
                     ].loc[2870:2917]
x337_340_paryer_1 = df_data_paragraph.loc[(df_data_paragraph.style_left.str.contains(""))&
                     (df_data_paragraph.VALUE.str.contains(""))
                     ].loc[2909:2910]
x337_340_shermon_1 = df_data_paragraph.loc[(df_data_paragraph.style_left.str.contains(""))&
                     (df_data_paragraph.VALUE.str.contains(""))
                     ].loc[2890:2901]
x337_340_worship_1 = df_data_paragraph.loc[(df_data_paragraph.style_left.str.contains("993"))&
                     (df_data_paragraph.VALUE.str.contains(""))
                     ].loc[2870:2917]
df_data_paragraph.loc[(df_data_paragraph.index.to_series().apply(lambda x: x in x337_340_1.index))&
                      (df_data_paragraph.index.to_series().apply(lambda x: x not in x337_340_paryer_1.index))&
                      (df_data_paragraph.index.to_series().apply(lambda x: x not in x337_340_shermon_1.index))&
                      (df_data_paragraph.index.to_series().apply(lambda x: x not in x337_340_worship_1.index))
                      ,'label_id']=1
df_data_paragraph.loc[(df_data_paragraph.index.to_series().apply(lambda x: x in x337_340_1.index))&
                      (df_data_paragraph.index.to_series().apply(lambda x: x not in x337_340_paryer_1.index))&
                      (df_data_paragraph.index.to_series().apply(lambda x: x not in x337_340_shermon_1.index))&
                      (df_data_paragraph.index.to_series().apply(lambda x: x not in x337_340_worship_1.index))
                      ,'label']="Announcement"

# 341-345 2924:2985
x341_345_1 = df_data_paragraph.loc[(df_data_paragraph.style_left.str.contains(""))&
                     (df_data_paragraph.VALUE.str.contains(""))
                     ].loc[2924:2985]
x341_345_paryer_1 = df_data_paragraph.loc[(df_data_paragraph.style_left.str.contains(""))&
                     (df_data_paragraph.VALUE.str.contains(""))
                     ].loc[2973:2974]
x341_345_shermon_1 = df_data_paragraph.loc[(df_data_paragraph.style_left.str.contains("567"))&
                     (df_data_paragraph.VALUE.str.contains(""))
                     ].loc[2948:2953]
x341_345_worship_1 = df_data_paragraph.loc[(df_data_paragraph.style_left.str.contains(""))&
                     (df_data_paragraph.VALUE.str.contains(""))
                     ].loc[2998:3001]
df_data_paragraph.loc[(df_data_paragraph.index.to_series().apply(lambda x: x in x341_345_1.index))&
                      (df_data_paragraph.index.to_series().apply(lambda x: x not in x341_345_paryer_1.index))&
                      (df_data_paragraph.index.to_series().apply(lambda x: x not in x341_345_shermon_1.index))&
                      (df_data_paragraph.index.to_series().apply(lambda x: x not in x341_345_worship_1.index))
                      ,'label_id']=1
df_data_paragraph.loc[(df_data_paragraph.index.to_series().apply(lambda x: x in x341_345_1.index))&
                      (df_data_paragraph.index.to_series().apply(lambda x: x not in x341_345_paryer_1.index))&
                      (df_data_paragraph.index.to_series().apply(lambda x: x not in x341_345_shermon_1.index))&
                      (df_data_paragraph.index.to_series().apply(lambda x: x not in x341_345_worship_1.index))
                      ,'label']="Announcement"

# 345-349 2954:3030
x345_349_1 = df_data_paragraph.loc[(df_data_paragraph.style_left.str.contains(""))&
                     (df_data_paragraph.VALUE.str.contains(""))
                     ].loc[2988:3030]
x345_349_paryer_1 = df_data_paragraph.loc[(df_data_paragraph.style_left.str.contains(""))&
                     (df_data_paragraph.VALUE.str.contains(""))
                     ].loc[3021:3023]
x345_349_shermon_1 = df_data_paragraph.loc[(df_data_paragraph.style_left.str.contains("567"))&
                     (df_data_paragraph.VALUE.str.contains(""))
                     ].loc[3004:3011]
x345_349_worship_1 = df_data_paragraph.loc[(df_data_paragraph.style_left.str.contains("567"))&
                     (df_data_paragraph.VALUE.str.contains(""))
                     ].loc[2988:3030]
x345_349_worship_2 = df_data_paragraph.loc[(df_data_paragraph.style_left.str.contains(""))&
                     (df_data_paragraph.VALUE.str.contains(""))
                     ].loc[2998:3001]
df_data_paragraph.loc[(df_data_paragraph.index.to_series().apply(lambda x: x in x345_349_1.index))&
                      (df_data_paragraph.index.to_series().apply(lambda x: x not in x345_349_paryer_1.index))&
                      (df_data_paragraph.index.to_series().apply(lambda x: x not in x345_349_shermon_1.index))&
                      (df_data_paragraph.index.to_series().apply(lambda x: x not in x345_349_worship_1.index))&
                      (df_data_paragraph.index.to_series().apply(lambda x: x not in x345_349_worship_2.index))
                      ,'label_id']=1
df_data_paragraph.loc[(df_data_paragraph.index.to_series().apply(lambda x: x in x345_349_1.index))&
                      (df_data_paragraph.index.to_series().apply(lambda x: x not in x345_349_paryer_1.index))&
                      (df_data_paragraph.index.to_series().apply(lambda x: x not in x345_349_shermon_1.index))&
                      (df_data_paragraph.index.to_series().apply(lambda x: x not in x345_349_worship_1.index))&
                      (df_data_paragraph.index.to_series().apply(lambda x: x not in x345_349_worship_2.index))
                      ,'label']="Announcement"

In [24]:
x345_349_worship_2

,TYPE,VALUE,style_type,style_left,style_hanging,numPr_type,numPr_ilvl,numPr_id,label_id,label
2998,text,Kami akan pergi kepada siapa? Ooo.....,CT_Ind,[],[],[],[],[],4,Worship
2999,text,Sabda-Mu sabda hidup abadi! Ooo.....,CT_Ind,[],[],[],[],[],4,Worship
3000,text,"Kami percaya, Engkaulah Kristus,",CT_Ind,[],[],[],[],[],4,Worship
3001,text,Kau Yang Kudus dari Allah!,CT_Ind,[],[],[],[],[],4,Worship

In [25]:
# Shermon - umum
# 345-349 2954:3030
df_data_paragraph.loc[(df_data_paragraph.style_left.str.contains("567"))&
                     (df_data_paragraph.VALUE.str.contains(""))
                     ].loc[3004:3011]

,TYPE,VALUE,style_type,style_left,style_hanging,numPr_type,numPr_ilvl,numPr_id,label_id,label
3004,text,"Ya Bapa, Ke Dalam Tangan-Mu,",CT_Ind,567,[],[],[],[],3,Shermon
3005,text,Kuserahkan Nyawa-Ku,CT_Ind,567,[],[],[],[],3,Shermon
3006,text,Inilah kalimat terkahir yang diserukan dengan ...,CT_Ind,567,[],[],[],[],3,Shermon
3007,text,"Yesus memakai kata-kata bapa leluhur-Nya, yait...",CT_Ind,567,[],[],[],[],3,Shermon
3008,text,"Yesus memanggil Allah dengan sebutan ""Bapa"". S...",CT_Ind,567,[],[],[],[],3,Shermon
3009,text,Yesus sengaja memakai kalimat itu untuk menunj...,CT_Ind,567,[],[],[],[],3,Shermon
3010,text,Yesus memperlihatkan bagaimana Ia bersandar ke...,CT_Ind,567,[],[],[],[],3,Shermon
3011,text,Yesus telah memberi contoh dengan menerapkan k...,CT_Ind,567,[],[],[],[],3,Shermon

In [26]:
# Announcement 
df_data_paragraph.loc[(df_data_paragraph.style_left.str.contains(""))&
                     (df_data_paragraph.VALUE.str.contains(""))
                     ].loc[2988:3030]

,TYPE,VALUE,style_type,style_left,style_hanging,numPr_type,numPr_ilvl,numPr_id,label_id,label
2988,text,2.\tNYANYIAN,CT_Ind,567,563,[],[],[],4,Worship
2989,text,Angkatlah Gita Baru - PKJ 298,CT_Ind,567,[],[],[],[],4,Worship
2990,text,(dinyanyikan berulang-ulang 5x),CT_Ind,567,[],[],[],[],4,Worship
2991,text,Angkatlah gita baru:,CT_Ind,567,[],[],[],[],4,Worship
2992,text,"puji Tuhan selalu, puji Tuhan selalu!",CT_Ind,567,[],[],[],[],4,Worship
2993,text,Oooo........ooo......,CT_Ind,567,[],[],[],[],4,Worship
2994,text,3.\tDOA,CT_Ind,567,563,[],[],[],4,Worship
2995,text,4.\tNYANYIAN,CT_Ind,567,563,[],[],[],4,Worship
2996,text,Kami Akan Pergi Kepada Siapa - PKJ 303,CT_Ind,[],[],[],[],[],1,Announcement
2997,text,(Dinyanyikan berulang-ulang 5x),CT_Ind,[],[],[],[],[],1,Announcement
2998,text,Kami akan pergi kepada siapa? Ooo.....,CT_Ind,[],[],[],[],[],4,Worship
2999,text,Sabda-Mu sabda hidup abadi! Ooo.....,CT_Ind,[],[],[],[],[],4,Worship
3000,text,"Kami percaya, Engkaulah Kristus,",CT_Ind,[],[],[],[],[],4,Worship
3001,text,Kau Yang Kudus dari Allah!,CT_Ind,[],[],[],[],[],4,Worship
3002,text,5.\tPEMBACAAN ALKITAB: Lukas 23:46,CT_Ind,567,563,[],[],[],4,Worship
3003,text,6.\tRENUNGAN,CT_Ind,567,563,[],[],[],4,Worship
3004,text,"Ya Bapa, Ke Dalam Tangan-Mu,",CT_Ind,567,[],[],[],[],3,Shermon
3005,text,Kuserahkan Nyawa-Ku,CT_Ind,567,[],[],[],[],3,Shermon
3006,text,Inilah kalimat terkahir yang diserukan dengan ...,CT_Ind,567,[],[],[],[],3,Shermon
3007,text,"Yesus memakai kata-kata bapa leluhur-Nya, yait...",CT_Ind,567,[],[],[],[],3,Shermon
3008,text,"Yesus memanggil Allah dengan sebutan ""Bapa"". S...",CT_Ind,567,[],[],[],[],3,Shermon
3009,text,Yesus sengaja memakai kalimat itu untuk menunj...,CT_Ind,567,[],[],[],[],3,Shermon
3010,text,Yesus memperlihatkan bagaimana Ia bersandar ke...,CT_Ind,567,[],[],[],[],3,Shermon
3011,text,Yesus telah memberi contoh dengan menerapkan k...,CT_Ind,567,[],[],[],[],3,Shermon
3012,text,7.\tNYANYIAN,CT_Ind,567,563,[],[],[],4,Worship
3013,text,Ke Dalam Tangan Bapa,CT_Ind,567,[],[],[],[],4,Worship
3014,text,(In Manus Tuas Pater),CT_Ind,567,[],[],[],[],4,Worship
3015,text,(Dinyanyikan berulang-ulang 5x),CT_Ind,567,[],[],[],[],4,Worship
3016,text,"Ke dalam tangan Bapa,",CT_Ind,567,[],[],[],[],4,Worship
3017,text,aku serahkan hidupku.,CT_Ind,567,[],[],[],[],4,Worship
3018,text,"Ke dalam tangan Bapa,",CT_Ind,567,[],[],[],[],4,Worship
3019,text,aku serahkan hidupku,CT_Ind,567,[],[],[],[],4,Worship
3020,text,8.\tDOA,CT_Ind,567,563,[],[],[],4,Worship
3021,text,Memohon agar umat senantiasa percaya bahwa di ...,CT_Ind,993,426,numPr,0,131,2,Prayer
3022,text,Memohon agar umat senantiasa percaya bahwa seg...,CT_Ind,993,426,numPr,0,131,2,Prayer
3023,text,Mendoakan persekutuan agar menjadi persekutuan...,CT_Ind,993,426,numPr,0,131,2,Prayer
3024,text,9.\tNYANYIAN,CT_Ind,567,563,[],[],[],4,Worship
3025,text,Di Dunia Gelap - PKJ 301,CT_Ind,567,[],[],[],[],4,Worship
3026,text,(Dinyanyikan berulang-ulang 5x),CT_Ind,567,[],[],[],[],4,Worship
3027,text,"Di dunia gelap nyalakan api yang tak padam lagi,",CT_Ind,567,[],[],[],[],4,Worship
3028,text,tak padam lagi;,CT_Ind,567,[],[],[],[],4,Worship
3029,text,"di dunia gelap nylakan api tak padam lagi,",CT_Ind,567,[],[],[],[],4,Worship
3030,text,tak padam lagi di dunia gelap.,CT_Ind,567,[],[],[],[],4,Worship

In [27]:
# Song ~ tabrakan dengan  doa
df_data_paragraph.loc[(df_data_paragraph.style_left.str.contains("567"))&
                     (df_data_paragraph.VALUE.str.contains(""))
                     ].loc[2988:3030]

,TYPE,VALUE,style_type,style_left,style_hanging,numPr_type,numPr_ilvl,numPr_id,label_id,label
2988,text,2.\tNYANYIAN,CT_Ind,567,563,[],[],[],4,Worship
2989,text,Angkatlah Gita Baru - PKJ 298,CT_Ind,567,[],[],[],[],4,Worship
2990,text,(dinyanyikan berulang-ulang 5x),CT_Ind,567,[],[],[],[],4,Worship
2991,text,Angkatlah gita baru:,CT_Ind,567,[],[],[],[],4,Worship
2992,text,"puji Tuhan selalu, puji Tuhan selalu!",CT_Ind,567,[],[],[],[],4,Worship
2993,text,Oooo........ooo......,CT_Ind,567,[],[],[],[],4,Worship
2994,text,3.\tDOA,CT_Ind,567,563,[],[],[],4,Worship
2995,text,4.\tNYANYIAN,CT_Ind,567,563,[],[],[],4,Worship
3002,text,5.\tPEMBACAAN ALKITAB: Lukas 23:46,CT_Ind,567,563,[],[],[],4,Worship
3003,text,6.\tRENUNGAN,CT_Ind,567,563,[],[],[],4,Worship
3004,text,"Ya Bapa, Ke Dalam Tangan-Mu,",CT_Ind,567,[],[],[],[],3,Shermon
3005,text,Kuserahkan Nyawa-Ku,CT_Ind,567,[],[],[],[],3,Shermon
3006,text,Inilah kalimat terkahir yang diserukan dengan ...,CT_Ind,567,[],[],[],[],3,Shermon
3007,text,"Yesus memakai kata-kata bapa leluhur-Nya, yait...",CT_Ind,567,[],[],[],[],3,Shermon
3008,text,"Yesus memanggil Allah dengan sebutan ""Bapa"". S...",CT_Ind,567,[],[],[],[],3,Shermon
3009,text,Yesus sengaja memakai kalimat itu untuk menunj...,CT_Ind,567,[],[],[],[],3,Shermon
3010,text,Yesus memperlihatkan bagaimana Ia bersandar ke...,CT_Ind,567,[],[],[],[],3,Shermon
3011,text,Yesus telah memberi contoh dengan menerapkan k...,CT_Ind,567,[],[],[],[],3,Shermon
3012,text,7.\tNYANYIAN,CT_Ind,567,563,[],[],[],4,Worship
3013,text,Ke Dalam Tangan Bapa,CT_Ind,567,[],[],[],[],4,Worship
3014,text,(In Manus Tuas Pater),CT_Ind,567,[],[],[],[],4,Worship
3015,text,(Dinyanyikan berulang-ulang 5x),CT_Ind,567,[],[],[],[],4,Worship
3016,text,"Ke dalam tangan Bapa,",CT_Ind,567,[],[],[],[],4,Worship
3017,text,aku serahkan hidupku.,CT_Ind,567,[],[],[],[],4,Worship
3018,text,"Ke dalam tangan Bapa,",CT_Ind,567,[],[],[],[],4,Worship
3019,text,aku serahkan hidupku,CT_Ind,567,[],[],[],[],4,Worship
3020,text,8.\tDOA,CT_Ind,567,563,[],[],[],4,Worship
3024,text,9.\tNYANYIAN,CT_Ind,567,563,[],[],[],4,Worship
3025,text,Di Dunia Gelap - PKJ 301,CT_Ind,567,[],[],[],[],4,Worship
3026,text,(Dinyanyikan berulang-ulang 5x),CT_Ind,567,[],[],[],[],4,Worship
3027,text,"Di dunia gelap nyalakan api yang tak padam lagi,",CT_Ind,567,[],[],[],[],4,Worship
3028,text,tak padam lagi;,CT_Ind,567,[],[],[],[],4,Worship
3029,text,"di dunia gelap nylakan api tak padam lagi,",CT_Ind,567,[],[],[],[],4,Worship
3030,text,tak padam lagi di dunia gelap.,CT_Ind,567,[],[],[],[],4,Worship

In [28]:
# Song ~ tabrakan dengan  doa
df_data_paragraph.loc[(df_data_paragraph.style_left.str.contains(""))&
                     (df_data_paragraph.VALUE.str.contains(""))
                     ].loc[2998:3001]

,TYPE,VALUE,style_type,style_left,style_hanging,numPr_type,numPr_ilvl,numPr_id,label_id,label
2998,text,Kami akan pergi kepada siapa? Ooo.....,CT_Ind,[],[],[],[],[],4,Worship
2999,text,Sabda-Mu sabda hidup abadi! Ooo.....,CT_Ind,[],[],[],[],[],4,Worship
3000,text,"Kami percaya, Engkaulah Kristus,",CT_Ind,[],[],[],[],[],4,Worship
3001,text,Kau Yang Kudus dari Allah!,CT_Ind,[],[],[],[],[],4,Worship

In [29]:
# Prayer1
df_data_paragraph.loc[(df_data_paragraph.style_left.str.contains(""))&
                     (df_data_paragraph.VALUE.str.contains(""))
                     ].loc[3021:3023]

,TYPE,VALUE,style_type,style_left,style_hanging,numPr_type,numPr_ilvl,numPr_id,label_id,label
3021,text,Memohon agar umat senantiasa percaya bahwa di ...,CT_Ind,993,426,numPr,0,131,2,Prayer
3022,text,Memohon agar umat senantiasa percaya bahwa seg...,CT_Ind,993,426,numPr,0,131,2,Prayer
3023,text,Mendoakan persekutuan agar menjadi persekutuan...,CT_Ind,993,426,numPr,0,131,2,Prayer

# Lukas

In [30]:
df_data_paragraph['Unnamed: 0']=""
df_data_paragraph = df_data_paragraph[['Unnamed: 0','VALUE','label_id','label']].copy()

# Bastian

In [31]:
# Load CSV paragraph
df_data_paragraph_bastian = pd.read_csv('book_paskah_labeled_bastian_final.csv')
df_data_paragraph_bastian = df_data_paragraph_bastian[['Unnamed: 0','VALUE','label_id','label']].copy()

## 1_10

In [32]:
df_1_5_b = df_data_paragraph_bastian.loc[df_data_paragraph_bastian['Unnamed: 0']<=106].copy()

In [33]:
df_5_11_l = df_data_paragraph.loc[106:128].copy()

# 11-130

In [34]:
df_11_70_b = df_data_paragraph_bastian.loc[(df_data_paragraph_bastian['Unnamed: 0']>=129)&
                                           (df_data_paragraph_bastian['Unnamed: 0']<=427)].copy()
df_71_130_l = df_data_paragraph.loc[df_data_paragraph.label_id!=""].loc[427:1000].copy()

# 131-230

In [35]:
df_131_180_b = df_data_paragraph_bastian.loc[(df_data_paragraph_bastian['Unnamed: 0']>=673)&
                                           (df_data_paragraph_bastian['Unnamed: 0']<=1340)].copy()
df_181_230_l = df_data_paragraph.loc[df_data_paragraph.label_id!=""].loc[1340:2109].copy()

# 231-284

In [36]:
df_231_268_b = df_data_paragraph_bastian.loc[(df_data_paragraph_bastian['Unnamed: 0']>=2109)&
                                           (df_data_paragraph_bastian['Unnamed: 0']<=2375)].copy()
df_269_284_l = df_data_paragraph.loc[df_data_paragraph.label_id!=""].loc[2375:2474].copy()

# 285-314

In [37]:
df_285_296_b = df_data_paragraph_bastian.loc[(df_data_paragraph_bastian['Unnamed: 0']>=2475)&
                                           (df_data_paragraph_bastian['Unnamed: 0']<=2558)].copy()
df_297_314_l = df_data_paragraph.loc[df_data_paragraph.label_id!=""].loc[2558:2684].copy()

# 315-350

In [38]:
df_315_332_b = df_data_paragraph_bastian.loc[(df_data_paragraph_bastian['Unnamed: 0']>=2685)&
                                           (df_data_paragraph_bastian['Unnamed: 0']<=2820)].copy()
df_333_350_l = df_data_paragraph.loc[df_data_paragraph.label_id!=""].loc[2821:3030].copy()
df_351_selesai_b = df_data_paragraph_bastian.loc[(df_data_paragraph_bastian['Unnamed: 0']>=3030)].copy()

In [39]:
# df_data_paragraph.loc[df_data_paragraph.label_id!=""].loc[2821:3030] #2821:3030

In [40]:
# df_data_paragraph.loc[df_data_paragraph.label_id==""].loc[3030:]

# Merge all data frame

In [41]:
df_finished = pd.concat([df_1_5_b,df_5_11_l,df_11_70_b,df_71_130_l,df_131_180_b,
                         df_181_230_l,df_231_268_b,df_269_284_l,df_285_296_b,df_297_314_l,
                        df_315_332_b,df_333_350_l,df_351_selesai_b
                        ]).copy()
del df_finished['Unnamed: 0']

In [44]:
# df_finished.to_csv('book_pashkah_labeled_paragraf.csv',index=False)

# Split to sentence

In [42]:
import nltk
from Sastrawi.Stemmer.StemmerFactory import StemmerFactory
# Stemming + casefolding + remove punctuation

list_container_data_clean = []

for datas in df_finished.values: 
    sentences =  nltk.sent_tokenize(datas[0])
    for sen_text in sentences:
        list_data_clean = []
        stemmer = StemmerFactory()
        stemmer_fact = stemmer.create_stemmer()
        result_stemmer = stemmer_fact.stem(sen_text)
        list_data_clean.append(result_stemmer)
        list_data_clean.append(datas[1])
        list_data_clean.append(datas[2])
        list_container_data_clean.append(list_data_clean)

In [43]:
# Convert to Pandas
df_final_sentence_okay = pd.DataFrame(list_container_data_clean, columns =['VALUE', 'label_id','label'])

In [44]:
## Dumb it
# df_final_sentence_okay.to_csv('book_paskah_labeled.csv')

# Test Prapare data to label studio [Fix]
Custom coloum from dara

In [47]:
# Versi1
df_final_sentence_announcement = df_final_sentence_okay.loc[df_final_sentence_okay.label_id==1].copy()
del df_final_sentence_announcement['label_id']
del df_final_sentence_announcement['label']

In [51]:
df_final_sentence_announcement = df_final_sentence_announcement.rename(columns={'VALUE':'text'}).copy()
df_final_sentence_announcement.to_csv('labeled/book_paskah_labeled_announcement.csv',index=False)

In [54]:
# Versi2
df_final_sentence_announcement = df_final_sentence_okay.copy()
df_final_sentence_announcement = df_final_sentence_announcement.rename(columns={'VALUE':'text'}).copy()
df_final_sentence_announcement.to_csv('labeled/book_paskah_labeled_announcement.csv',index=False)